apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-newrelic
spec:
  privileged: true  
  hostNetwork: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'